### ISSUE TITLE
 Wrong parameters for Cronofy\Exception\CronofyException

### ISSUE THREAD

**Issue by japel** [cronofy/cronofy-php#128]
This error seems to occur when the cronofy API returns 429 (Too Many Requests). 

Error: Wrong parameters for Cronofy\Exception\CronofyException([string $message [, long $code [, Throwable $previous = NULL]]]) in /vendor/cronofy/cronofy/src/Exception/CronofyException.php:15
Stack trace:
#0 /vendor/cronofy/cronofy/src/Exception/CronofyException.php(15): Exception->__construct(NULL, 429, NULL)
#1 /vendor/cronofy/cronofy/src/Cronofy.php(1109): Cronofy\Exception\CronofyException->__construct(NULL, 429, '')
#2 /vendor/cronofy/cronofy/src/Cronofy.php(76): Cronofy\Cronofy->handleResponse('', 429)
#3 /vendor/cronofy/cronofy/src/Cronofy.php(86): Cronofy\Cronofy->baseHttpGet('/v1/availabilit...', Array, Array)
#4 /vendor/cronofy/cronofy/src/Cronofy.php(972): Cronofy\Cronofy->httpGet('/v1/availabilit...')

CronofyException is tried to be initialized with NULL, 429, NULL, but CronofyException requires a message, which is normally taken from $http_codes which does not include a message for 429

**Comment by japel** [comment]
closing this as it seems in newest version there is a message defined for 429 on $http_codes
